### PR TITLE
Feature/travis docker

### PR DESCRIPTION
**Pull request by mion00**
Fixed the build process on Travis.

Travis now builds the same containers used in development (except with some additional packages for capybara-webkit).
This assure us that the tests run in the exact same environment, without having to worry of dependencies problems and other deployment factors. (If it works on Docker, it works anywhere Docker runs! :+1: )

It runs rspec inside the container, using docker-compose to bootstrap all the other services (db, redis, sidekiq and solr)
Here is the build resulting from this commit: https://travis-ci.org/mion00/Airesis/builds/101959328

The test fails because Capybara fails to find some buttons, but at least now it won't output some strange EFIFO errors!

### CODE REVIEW

**Comment by mion00** [comment]
Fixed the build in Travis: https://travis-ci.org/mion00/Airesis/builds/102116310
I forgot to add the ci_ignore rule in running rspec and I specified the schulze-vote version in Gemfile. The latest version of the gem doesn't work.

**Comment by mion00** [comment]
I am rebasing this PR on top of develop to fix the merge conflicts..

**Comment by coorasse** [comment]
I have enabled travis again. update the pull request and it should start

**Comment by mion00** [comment]
Done!

**Comment by coorasse** [comment]
suuuper coool! thank you!

**Pull request merged**
